version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password | docker login --username AWS --password-stdin 813260210012.dkr.ecr.eu-west-1.amazonaws.com 
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t icdl:latest .
      - docker tag icdl:latest 813260210012.dkr.ecr.eu-west-1.amazonaws.com/icdl:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 813260210012.dkr.ecr.eu-west-1.amazonaws.com/icdl:latest